[package]
name = "bilgi-guvenligi"
version = "0.1.0"
edition = "2024"

[dependencies]
http-body-util = "0.1.3"
hyper = { version = "1.8.1", features = ["full"] }
hyper-util = { version = "0.1.18", features = ["full"]}
steganography = "1.0.2"
tokio = { version = "1.48.0", features = ["full"] }
